Repository Dario-Cabrera/Frontend-Medical_Rolling, pull requests merged in 2024-05, with the labels that each got.

#31 Feature-028 (Create User-Doctor-Appoinments en Auditor)
  package-lock.json
  package.json
  src/App.jsx
  src/Components/Wrappers/Table.jsx
  src/Context/DoctorContext.jsx
  src/Context/UserContext.jsx
  src/Views/AppointmentFormPage.jsx
  src/Views/RegisterPageUser.jsx
Labels: enhancement

#32 Feature-032 (Estilos Front)
  src/App.jsx
  src/Components/Wrappers/AppointmentCard.jsx
  src/Components/Wrappers/AppointmentCardHistory.jsx
  src/Components/Wrappers/CarouselHero.jsx
  src/Components/Wrappers/CarouselPlans.jsx
  src/Components/Wrappers/ServicesSection.jsx
  src/Views/AboutUs.jsx
  src/Views/ContactPage.jsx
  src/Views/LoginPagesUser.jsx
  src/Views/PagesDoctorAppointmentManagement.jsx
  src/Views/PagesUserAppointmentManagement.jsx
  src/Views/RegisterPageUser.jsx
Labels: enhancement, errors correction

#34 History-029 (Corrección Navbar)
  src/App.jsx
  src/Components/Wrappers/AppointmentCard.jsx
  src/Components/Wrappers/AppointmentCardHistory.jsx
  src/Components/Wrappers/CarouselHero.jsx
  src/Components/Wrappers/CarouselPlans.jsx
  src/Components/Wrappers/Navbar.jsx
  src/Components/Wrappers/ServicesSection.jsx
  src/Context/UserContext.jsx
  src/ProtectedRouteDoctor.jsx
  src/Routes/ProtectedRouteAuditor.jsx
  src/Routes/ProtectedRouteDoctor.jsx
  src/Routes/ProtectedRouteUser.jsx
  src/Routes/ProtectedRoutes.jsx
  src/Views/AboutUs.jsx
  src/Views/ContactPage.jsx
  src/Views/LoginPagesUser.jsx
  src/Views/PagesDoctorAppointmentManagement.jsx
  src/Views/PagesUserAppointmentManagement.jsx
  src/Views/RegisterPageDoctor.jsx
  src/Views/RegisterPageUser.jsx
Labels: enhancement, errors correction

#35 Feature 037
  src/App.jsx
  src/Components/Wrappers/AppointmentCard.jsx
  src/Components/Wrappers/AppointmentCardHistory.jsx
  src/Components/Wrappers/CarouselHero.jsx
  src/Components/Wrappers/CarouselPlans.jsx
  src/Components/Wrappers/Footer.jsx
  src/Components/Wrappers/Navbar.jsx
  src/Components/Wrappers/Table.jsx
  src/Context/AppointmentContext.jsx
  src/Context/DoctorContext.jsx
  src/Context/UserContext.jsx
  src/Routes/ProtectedRouteAuditor.jsx
  src/Routes/ProtectedRouteDoctor.jsx
  src/Routes/ProtectedRouteUser.jsx
  src/Views/AppointmentFormPage.jsx
  src/Views/ContactPage.jsx
  src/Views/ContactUs.jsx
  src/Views/LoginPagesDoctor.jsx
  src/Views/LoginPagesUser.jsx
  src/Views/PagesDoctorAppointmentManagement.jsx
  src/Views/PagesUserAppointmentManagement.jsx
  src/api/appointment.auth.js
  src/api/doctor.auth.js
Labels: enhancement, errors correction

#36 History-036 (Correcciones finales)
  src/App.jsx
  src/Components/Wrappers/AppointmentCard.jsx
  src/Components/Wrappers/AppointmentCardHistory.jsx
  src/Components/Wrappers/CarouselHero.jsx
  src/Components/Wrappers/CarouselPlans.jsx
  src/Components/Wrappers/Footer.jsx
  src/Components/Wrappers/Navbar.jsx
  src/Components/Wrappers/Table.jsx
  src/Context/AppointmentContext.jsx
  src/Context/DoctorContext.jsx
  src/Context/UserContext.jsx
  src/Routes/ProtectedRouteAuditor.jsx
  src/Routes/ProtectedRouteDoctor.jsx
  src/Routes/ProtectedRouteUser.jsx
  src/Views/AppointmentFormPage.jsx
  src/Views/ContactPage.jsx
  src/Views/ContactUs.jsx
  src/Views/LoginPagesDoctor.jsx
  src/Views/LoginPagesUser.jsx
  src/Views/PagesDoctorAppointmentManagement.jsx
  src/Views/PagesUserAppointmentManagement.jsx
  src/api/appointment.auth.js
  src/api/doctor.auth.js
Labels: enhancement

#39 Feature 039 (Corrección Estilos - Contact Page)
  src/Components/Wrappers/AppointmentCard.jsx
  src/Components/Wrappers/AppointmentCardHistory.jsx
  src/Components/Wrappers/CarouselPlans.jsx
  src/Views/ContactPage.jsx
  src/Views/PagesUserAppointmentManagement.jsx
Labels: errors correction

#41 History 038 (Corrección de errores - Estilos)
  src/Components/Wrappers/AppointmentCard.jsx
  src/Components/Wrappers/AppointmentCardHistory.jsx
  src/Components/Wrappers/CarouselPlans.jsx
  src/Views/ContactPage.jsx
  src/Views/PagesUserAppointmentManagement.jsx
Labels: errors correction

#42 Develop
  src/Components/Wrappers/AppointmentCard.jsx
  src/Components/Wrappers/AppointmentCardHistory.jsx
  src/Components/Wrappers/CarouselPlans.jsx
  src/Views/ContactPage.jsx
  src/Views/PagesUserAppointmentManagement.jsx
Labels: enhancement, errors correction

#48 Feature-043 (Botones Contacto)
  src/Views/ContactUs.jsx
Labels: enhancement, errors correction

#49 Feature-045 (Eliminar comentarios y código comentado)
  src/App.jsx
  src/Components/Wrappers/AppointmentCard.jsx
  src/Components/Wrappers/CarouselPlans.jsx
  src/Components/Wrappers/Footer.jsx
  src/Components/Wrappers/Navbar.jsx
  src/Components/Wrappers/ServicesSection.jsx
  src/Components/Wrappers/Table.jsx
  src/Context/DoctorContext.jsx
  src/Context/UserContext.jsx
  src/Routes/ProtectedRoutes.jsx
  src/Views/AppointmentFormPage.jsx
  src/Views/ContactPage.jsx
  src/Views/ContactUs.jsx
  src/Views/Homepage.jsx
  src/Views/PagesDoctorAppointmentManagement.jsx
  src/Views/PagesUserAppointmentManagement.jsx
  src/api/appointment.auth.js
  src/api/doctor.auth.js
  src/api/user.auth.js
  tailwind.config.js
  vite.config.js
Labels: enhancement, errors correction

#50 Feature-044 (Corregir Footer)
  src/App.jsx
  src/Views/PagesDoctorAppointmentManagement.jsx
  src/Views/PagesUserAppointmentManagement.jsx
Labels: enhancement

#51 Feature-042 (Formulario Contacto - Formulario Registro)
  src/Views/ContactPage.jsx
  src/Views/ContactUs.jsx
  src/Views/RegisterPageUser.jsx
Labels: errors correction

#52 History-041 (Corrección Errores QA)
  src/App.jsx
  src/Components/Wrappers/AppointmentCard.jsx
  src/Components/Wrappers/CarouselPlans.jsx
  src/Components/Wrappers/Footer.jsx
  src/Components/Wrappers/Navbar.jsx
  src/Components/Wrappers/ServicesSection.jsx
  src/Components/Wrappers/Table.jsx
  src/Context/DoctorContext.jsx
  src/Context/UserContext.jsx
  src/Routes/ProtectedRoutes.jsx
  src/Views/AppointmentFormPage.jsx
  src/Views/ContactPage.jsx
  src/Views/ContactUs.jsx
  src/Views/Homepage.jsx
  src/Views/PagesDoctorAppointmentManagement.jsx
  src/Views/PagesUserAppointmentManagement.jsx
  src/Views/RegisterPageUser.jsx
  src/api/appointment.auth.js
  src/api/doctor.auth.js
  src/api/user.auth.js
  tailwind.config.js
  vite.config.js
Labels: enhancement
